[project]
name = "cps-cosimulation-env"
version = "0.1.0"
description = "Python CPS co-simulation environment"
authors = [
    {name = "Will Stuckey", email = "guyfleeman@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "scipy>=1.11.2",
    "PYPOWER>=5.1.16",
    "helics>=3.4.0",
    "matplotlib>=3.8.0",
    "dnp3>=1.0.0",
]

# We build our own DNP3 Python package in the dnp3 directory
# Specifying the path here means it will automatically get built
# and installed when uv is looking for the dnp3 dependency
[tool.uv.sources]
dnp3 = { path = "./python-dnp3", editable = false }

